{% set version = "8.1.1" %}

{% set migrating = False %}
{% set migrating = True %}  # [win and python_impl == 'pypy']

package:
  name: ipython
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipython/ipython-{{ version }}.tar.gz
  sha256: 8138762243c9b3a3ffcf70b37151a2a35c23d3a29f9743878c33624f4207be3d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  skip: true  # [py<37]
  script_env:
    # Use MIGRATING environment variable instead of duplicating conditions into run_test.py.
    # Combine script_env stanzas to avoid clobber
    - MIGRATING={{ migrating }}
    - IPYTHON_TESTING_TIMEOUT_SCALE=5
  entry_points:
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython
    - iptest = IPython.testing.iptestcontroller:main
    - iptest3 = IPython.testing.iptestcontroller:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - appnope  # [osx]
    - backcall
    - colorama  # [win]
    - decorator
    - jedi >=0.16
    # earlier versions depended on ipython
    - matplotlib-inline >=0.1.2
    - pexpect >4.3  # [unix]
    - pickleshare
    - prompt-toolkit >=2.0.0,!=3.0.0,!=3.0.1,<3.1.0
    - pygments
    - python
    - setuptools >=18.5
    - traitlets >=4.2

test:
  requires:
    - pip
    {% if not migrating %}
    - curio  # [unix]
    - ipykernel
    - matplotlib-base
    - nbformat
    - nose >=0.10.1
    - numpy >=1.17
    - pytest
    - pygments
    - requests
    - testpath
    - trio
    {% endif %}

  imports:
    - IPython
    - IPython.core
    - IPython.core.magics
    - IPython.core.tests
    - IPython.extensions
    - IPython.extensions.tests
    - IPython.external
    - IPython.external.decorators
    - IPython.lib
    - IPython.lib.tests
    - IPython.sphinxext
    - IPython.terminal
    - IPython.terminal.pt_inputhooks
    - IPython.terminal.tests
    - IPython.testing
    - IPython.testing.plugin
    - IPython.testing.tests
    - IPython.utils
    - IPython.utils.tests
  commands:
    - pip check
    - ipython -h
    - ipython3 -h
    {% if not migrating %}
    - iptest -h
    - iptest3 -h
    {% endif %}

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IPython: Productive Interactive Computing'
  description: |
    IPython provides a rich architecture for interactive computing with
    a powerful interactive shell, a kernel for Jupyter, high performance
    tools for parallel computing, and more.
  doc_url: https://ipython.readthedocs.io
  dev_url: https://github.com/ipython/ipython

extra:
  recipe-maintainers:
    - Carreau
    - jakirkham
    - fperez
    - ellisonbg
    - minrk
    - ocefpaf
    - pelson
    - takluyver
    - bollwyvl
    - blink1073
