{% set name = "ipython" %}
{% set version = "8.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 40b60e15b22591450eef73e40a027cf77bd652e757523eebc5bd7c7c498290eb
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]
  entry_points:
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - colorama  # [win]
    - decorator
    - exceptiongroup  # [py<311]
    - jedi >=0.16
    - matplotlib-inline
    - pexpect >4.3  # [not win]
    - prompt_toolkit >=3.0.41,<3.1.0
    - pygments >=2.4.0
    - stack_data
    - traitlets >=5.13.0
    - typing_extensions >=4.6 # [py<312]

test:
  source_files:
    - setup.py
  imports:
    - IPython
    - IPython.conftest
    - IPython.core
    - IPython.core.magics
    - IPython.extensions
    # - IPython.external.qt_for_kernel
    # - IPython.external.qt_loaders
    - IPython.lib
    - IPython.paths
    # - IPython.sphinxext.ipython_console_highlighting
    - IPython.terminal.debugger
    - IPython.terminal.embed
    - IPython.terminal.interactiveshell
    - IPython.terminal.magics
    - IPython.terminal.prompts
    - IPython.terminal.pt_inputhooks
    - IPython.terminal.pt_inputhooks.asyncio
    # - IPython.terminal.pt_inputhooks.glut
    # - IPython.terminal.pt_inputhooks.gtk
    # - IPython.terminal.pt_inputhooks.gtk3
    # - IPython.terminal.pt_inputhooks.gtk4
    - IPython.terminal.pt_inputhooks.osx
    # - IPython.terminal.pt_inputhooks.pyglet
    # - IPython.terminal.pt_inputhooks.qt
    # - IPython.terminal.pt_inputhooks.tk
    # - IPython.terminal.pt_inputhooks.wx
    - IPython.terminal.ptutils
    - IPython.terminal.shortcuts
    - IPython.terminal.shortcuts.auto_match
    - IPython.terminal.shortcuts.auto_suggest
    - IPython.terminal.shortcuts.filters
    # - IPython.utils._process_cli
    - IPython.utils._process_common
    - IPython.utils._process_emscripten
    - IPython.utils._process_posix
    - IPython.utils.capture
    - IPython.utils.coloransi
    - IPython.utils.contexts
    - IPython.utils.data
    - IPython.utils.decorators
    - IPython.utils.dir2
    - IPython.utils.encoding
    - IPython.utils.frame
    - IPython.utils.generics
    - IPython.utils.importstring
    - IPython.utils.io
    - IPython.utils.ipstruct
    - IPython.utils.module_paths
    - IPython.utils.openpy
    - IPython.utils.process
    - IPython.utils.py3compat
    - IPython.utils.sentinel
    - IPython.utils.shimmodule
    - IPython.utils.strdispatch
    - IPython.utils.sysinfo
    - IPython.utils.syspathcontext
    - IPython.utils.tempdir
    - IPython.utils.terminal
    - IPython.utils.timing
    - IPython.utils.tokenutil
    # - IPython.utils.tz
    - IPython.utils.ulinecache
    # - IPython.utils.version
    - IPython.utils.wildcard
    # - IPython.terminal.pt_inputhooks
    - IPython.terminal.tests
    - IPython.testing
    - IPython.testing.plugin
    - IPython.testing.plugin.pytest_ipdoctest
    - IPython.testing.tests
    - IPython.utils.tests
  requires:
    - pip
    - pytest
    - pytest-asyncio <0.22
    - testpath
    - pickleshare
    - packaging
    - curio
    - matplotlib-base !=3.2.0
    - nbformat
    - numpy >=1.23
    - pandas
    - trio
    - jupyter_client
  commands:
    - pip check
    - pygmentize -L | grep ipython
    - ipython -h
    - ipython3 -h
     {% set pytest_args = " --ignore-glob=consoleapp.py" %}
     {% set pytest_args = pytest_args + " --ignore-glob=external/*.py" %}
     {% set pytest_args = pytest_args + " --ignore-glob=sphinxext/*.py" %}
     {% set pytest_args = pytest_args + " --ignore-glob=terminal/console*.py" %}
     {% set pytest_args = pytest_args + " --ignore-glob=terminal/pt_inputhooks/*.py" %}
     {% set pytest_args = pytest_args + " --ignore-glob=utils/*.py" %}
    - python -m pytest -vv --pyargs IPython --maxfail=15 -k "not (decorator_skip or pprint_heap_allocated or system_interrupt)" {{ pytest_args }}

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IPython: Productive Interactive Computing'
  description: |
    IPython provides a rich architecture for interactive computing with
    a powerful interactive shell, a kernel for Jupyter, high performance
    tools for parallel computing, and more.
  doc_url: https://ipython.readthedocs.io
  dev_url: https://github.com/ipython/ipython

extra:
  recipe-maintainers:
    - Carreau
    - jakirkham
    - fperez
    - ellisonbg
    - minrk
    - ocefpaf
    - pelson
    - takluyver
    - bollwyvl
    - blink1073
