{% set name = "ipython" %}
{% set version = "9.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 129c44b941fe6d9b82d36fc7a7c18127ddb1d6f02f78f867f402e2e3adde3113

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<311]
  entry_points:
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - colorama  # [win]
    - decorator
    - ipython_pygments_lexers
    - jedi >=0.16
    - matplotlib-inline
    - pexpect >4.3  # [not win]
    - prompt_toolkit >=3.0.41,<3.1.0
    - pygments >=2.4.0
    - stack_data
    - traitlets >=5.13.0
    - typing_extensions >=4.6  # [py<312]

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-asyncio <0.22
    - testpath
    - pickleshare
    - curio
    - ipykernel
    - matplotlib-base !=3.2.0
    - nbclient
    - nbformat
    - numpy >=1.23
    - pandas
    - trio
    - python
  commands:
    - pip check
    - pygmentize -L | grep ipython  # [unix]
    - ipython -h
    - ipython3 -h
    - export MIGRATING=false  # [unix]
    # Newly added raise_on_interrupt tests failing
    - pytest tests -k "not (timeit_raise_on_interrupt or script_raise_on_interrupt or time_raise_on_interrupt)"

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "IPython: Productive Interactive Computing"
  description: |
    IPython provides a rich architecture for interactive computing with
    a powerful interactive shell, a kernel for Jupyter, high performance
    tools for parallel computing, and more.
  doc_url: https://ipython.readthedocs.io
  dev_url: https://github.com/ipython/ipython

extra:
  recipe-maintainers:
    - Carreau
    - jakirkham
    - fperez
    - ellisonbg
    - minrk
    - ocefpaf
    - pelson
    - takluyver
    - bollwyvl
    - blink1073
