{% set name = "ipython" %}
{% set version = "8.9.0" %}
{% set build_number = "0" %}
{% set checksum = "71618e82e6d59487bea059626e7c79fb4a5b760d1510d02fab1160db6fdfa1f7" %}
{% set migrating = false %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: {{ build_number }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  skip: true  # [py<38]
  script_env:
    - MIGRATING={{ migrating }}
    # TODO: investigate removing when some pypy/coverage speed issues are resolved
    - IPYTHON_TESTING_TIMEOUT_SCALE=10
    - COV_THRESHOLD=72  # [win]
    - COV_THRESHOLD=73  # [(linux and not ppc64le) or osx]
    # 2022/4/1: Tests fail on ppc64le with total coverage: 63.63%
    - COV_THRESHOLD=63  # [linux and ppc64le]
  entry_points:
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - appnope   # [osx]
    - backcall
    - colorama  # [win]
    - decorator
    - jedi >=0.16
    # earlier versions depended on ipython
    - matplotlib-inline >=0.1.2
    - pexpect >4.3  # [unix]
    - pickleshare
    - prompt-toolkit >3.0.11,<3.1.0
    - pygments >=2.4.0
    - stack_data
    - traitlets >=5

test:
  requires:
    - pip
    {% if not migrating %}
    - black
    - curio  # [unix]
    - matplotlib-base !=3.2.0
    - nbformat
    - numpy >=1.20
    - pandas
    - pygments
    - pytest <7.1
    - pytest-asyncio
    - pytest-cov
    - testpath
    - trio
    {% endif %}

  commands:
    - pip check
    - pygmentize -L | grep ipython
    - ipython -h
    - ipython3 -h

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IPython: Productive Interactive Computing'
  description: |
    IPython provides a rich architecture for interactive computing with
    a powerful interactive shell, a kernel for Jupyter, high performance
    tools for parallel computing, and more.
  doc_url: https://ipython.readthedocs.io
  dev_url: https://github.com/ipython/ipython

extra:
  recipe-maintainers:
    - Carreau
    - jakirkham
    - fperez
    - ellisonbg
    - minrk
    - ocefpaf
    - pelson
    - takluyver
    - bollwyvl
    - blink1073
