{% set name = "ipython" %}
{% set version = "9.10.0" %}
# When building out the initial package set for a new Python version the
# recommendation is to run basic tests only, then build
# matplotlib-base, pandas, trio,ipykernel, etc. and then run with `test_extra="yes"` to test all the tests.
{% set test_extra = "yes" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd9e656be97618a0676d058134cd44e6dc7012c0e5cb36a9ce96a8c904adaf77

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<311]
  entry_points:
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0
  run:
    - python
    - colorama >=0.4.4  # [win]
    - decorator >=4.3.2
    - ipython_pygments_lexers >=1.0.0
    - jedi >=0.18.1
    - matplotlib-inline >=0.1.5
    - pexpect >4.3  # [not win]
    - prompt_toolkit >=3.0.41,<3.1.0
    - pygments >=2.11.0
    - stack_data >=0.6.0
    - traitlets >=5.13.0
    - typing_extensions >=4.6  # [py<312]
  run_constrained:
    - argcomplete >=3.0

test:
  source_files:
    - tests
  requires:
    - pip
    - packaging >=20.1.0
    - pytest >=7.0.0
    - pytest-asyncio >=1.0.0
    - setuptools >=61.2
    - testpath >=0.2
# If test_extra: "yes" test all tests; otherwise test only the base tests for a new python version, e.g., py314.
{% if test_extra == 'yes' %}
    - curio
    - ipykernel >6.30
    # jupyter_ai is not available yet on the main channel
    #- jupyter_ai
    - matplotlib-base >3.9.0
    - nbclient
    - nbformat
    - numpy >=1.27
    - pandas >2.1
    - trio >=0.1.0
{% endif %}
  commands:
    - pip check
    - pygmentize -L | grep ipython  # [unix]
    - ipython -h
    - ipython3 -h
    - export MIGRATING=false  # [unix]
    # Newly added raise_on_interrupt tests failing
    # test_hist_file_config can fail randomly on osx-arm64 on CI
    - pytest tests -k "not (timeit_raise_on_interrupt or script_raise_on_interrupt or time_raise_on_interrupt or test_hist_file_config)"               # [not win]
    - pytest tests -k "not (timeit_raise_on_interrupt or script_raise_on_interrupt or time_raise_on_interrupt or test_hist_file_config or test_info)"  # [win]

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "IPython: Productive Interactive Computing"
  description: |
    IPython provides a rich architecture for interactive computing with
    a powerful interactive shell, a kernel for Jupyter, high performance
    tools for parallel computing, and more.
  doc_url: https://ipython.readthedocs.io
  dev_url: https://github.com/ipython/ipython

extra:
  recipe-maintainers:
    - Carreau
    - jakirkham
    - fperez
    - ellisonbg
    - minrk
    - ocefpaf
    - pelson
    - takluyver
    - bollwyvl
    - blink1073
