travis:
  secure:
    BINSTAR_TOKEN: 0YeCBr4vjFvq/SqkKKKm9FBZTZHBWuD+WUv5UJAlWmFtP0bsa0W50PG46rvlqBo5FVt9/DNOobGqEceyPQ6T/74bOYhxB/Hc99Fzt2pdjVDQmsAbcCf/h6kG6RZieAC0Fvw0MQ4NqTRhXYBq/TTH9Ux4x356plRG45gx/locACo51DzCG8PGC5LSJLe33bUWQrOH9JZjpNT/CnrjeM7aOYtIMNPnaLhaq0MGpHb+O6wteu1XHYwRuLHyF2r0Bq5GMr/A8WNnRih+bwIzNQFCd9ar1iE2HIIkkILn2JSAYVmZxfSZcYFyi0IuVa6qe+S2J9VRhn5n1e4x2ERISmHrY8tmQTmNz1hPAUztCZtJLuGIzFsW/EoXXCmlj4U2SLEqAaBgvWTMNESGt7dQ6B+jfk02kOdswHmBeciLX6TlYwWbL0weGHXaW+W+i9H7YfOshXYLGxoUADpIfzS+cZg4jIlpD75YIACfU9n+3b3mSuw3pgB6RdklI42c7WpWkMq9akxEJAumMMpXNYAL+IUXHm2fmaq5SWWr4O7Cz+rdqtX5O2yfMWkbaehIr+p60FjwGhPgMWm0H+aug6mnK6lNwCdZLiHSezEpS3SOiPawGna5MGOUHcj9Pcw0AX2grz03hvBaDryWpalUAq5YEvkILtg9Xi4qhwGlPRQhhLJF7xA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
